name: howl_and_seek
description: "QR code scavenger hunt web app project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  gradient_borders: ^1.0.1
  mobile_scanner: ^5.1.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - graphics/icons/
    - graphics/illustrations/

  # TODO: Add Poppins License to the License Registry
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 100
          style: normal
        - asset: fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic